# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:3.6

ADD bin/linux/git-sync /git-sync
ENV GIT_SYNC_DEST /git

RUN apk update --no-cache && apk add \
    ca-certificates \
    coreutils \
    git \
    openssh-client \
    shadow && \
    addgroup -S nginx && \
    adduser -S -g nginx nginx

RUN usermod -u 3005 nginx && groupmod -g 4005 nginx

USER nginx:nginx
ENTRYPOINT ["/git-sync"]
